### PR TITLE
Sheela aprameya js mini projects

### PR DESCRIPTION
**Pull request by saprameya**

### CODE REVIEW

**Comment by saprameya** [comment]
Hi, I am just beginning to explore github and open source projects.  Thanks for the opportunity to do so with this simple project.

**Comment by pratham2402** [comment]
Solve the issue in a separate pull request. One pull request for add a new mini-project and another one for solving the issue. Also, while posting PR for issue mention the issue tag. For the issue you are solving, mention #1. 
Also, a read-me file is required for all projects. A template has been provided for the same.

**Comment by pratham2402** [comment]
I have tagged the issue for you this time and have accepted your pull request. Also, add a read-me file for your project in the next PR.

**Comment by saprameya** [comment]
Hi, thanks so much for your reply. 
I added the readme file, not sure why it isn’t showing up. I’ll look into it. I need to explore more since I didn’t see the option to create another pull request. 
Honestly, you have no idea how much it means to me to be able to practice the whole process, being a newbie and self-teaching developer. 
Thank you for the opportunity.

**Comment by pratham2402** [comment]
The READ-ME file is visible. 👍No further PR's are required relating to either your To-do app or the issue. Keep up the great work! It's fantastic to see your enthusiasm and dedication to self-teaching. If you have any more questions or need further assistance, don't hesitate to reach out.

**Comment by saprameya** [comment]
Thank you!

**Pull request merged**
